name: Create Results Files
on:
  push:
    paths:
      - 'RESULTS/results.json'
  workflow_dispatch:

#    branches:
#      - main
#      - 'releases/**'

jobs:
  build_results:
    name: build_results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install requirements
        run: pip install -r scripts/requirements.txt
      - name: create files
        run: python scripts/generate_results_output.py
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Generated results'
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: 'RESULTS/*'
